modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="aicompanion"
version="1.0.0"
displayName="Minecraft Mini Build Mod"
description='''
A Minecraft mod that lets you create interactive miniature replicas of structures.
Features bidirectional synchronization, wall visibility toggle, and giant player visualization.
Perfect for architects and builders to design, test, and visualize their creations.
'''
authors="Mini Build Dev Team"

[[dependencies.aicompanion]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.aicompanion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
